- hosts: all
  tasks:
    - name: pull request dependent job
      debug:
        msg: "In Check label emea job"
        
    - name: testing of shiva
      debug:
       msg: "{{ zuul.change_url }}"
       
    - shell: |
         echo {{ zuul.change_url }} | cut -d '/' -f 7
      register: pullid
      
    - name: checking the canonical name
      debug:
       msg: "{{ zuul.project.name }}"
       
    - name: testing of kumar
      debug:
       msg: "{{ pullid }}"
       
    - set_fact:
       pull_id="{{pullid.stdout}}"
       
    - shell: |
           curl -s https://api.github.com/repos/{{ zuul.project.name }}/pulls/{{ pull_id }}/files | jq .contents_url
      register: url
      
    - set_fact:
       content_url="{{url.stdout}}"
      
    - shell: |
           curl -s "{{ content_url }}" | jq .content
      register: text
          
     - set_fact:
       decoded_text="{{ text | b64decode }}"

    - name: decode the encoded text
      debug:
        msg: "{{ decoded_text }}"
   
    - shell: |
          echo {{ decoded_text }} | awk -v FS="ROSbagDatalocation=" 'NF>1{print $2}
      register: build_location
      
      
    - shell: |
           esac
           
    
  #  - set_fact:
  #     decoded_file_content="{{ file_content | b64decode }}"
       
    - name: stdout the decoded data
      debug:
       msg: "{{ decoded_file_content }}"
    
 #   - name: "zuul return task"
 #     zuul_return:
 #       data:
 #         zuul_location: " {{ user_location }} "
