- hosts: all
  tasks:
    - debug:
        msg: "running for game of life demo"
      
    - shell: |
            echo {{ zuul.change_url }} | cut -d '/' -f 7
      register: pullid
 
    - name: "Deleted the workspace dir before build"
      shell: |
            rm -rf ~/work
      register: clean_output
      
    - name: Clone git repo
      git:
        repo: https://github.com/zuul-hcl-org/gameoflife.git
        dest: ~/work/
      when: clean_output is succeeded
      
    - name: Build sample project and junit reports 
      shell: |
            mvn -f ~/work/pom.xml clean install -s ~/.m2/settings.xml
            mvn -f ~/work/pom.xml surefire-report:report -s ~/.m2/settings.xml
      register: build_status
      
    - name: Push artifacts to jfrog repository
      uri:
        url: "{{ jfrog }}/artifactory/generic-local/gameoflife-{{ pullid.stdout }}.war"
        #when: zuul_location in emea
        validate_certs: no
        method: PUT
        headers:
          X-JFrog-Art-Api: "{{ jfrog_api_token }}"
        src: ~/work/gameoflife-web/target/gameoflife.war
        status_code: 201
        remote_src: yes
      when: build_status is succeeded
      
    - name: Upload junit and jacoco reports to logs dir
      synchronize:
        mode: pull
        src: /home/ec2-user/work/gameoflife-web/target/site/
        dest: "{{ zuul.executor.log_root }}/"
      when: build_status is succeeded
      
    - name: deploy to tomcat server
      shell: |
             cp ~/work/gameoflife-web/target/gameoflife.war /home/ec2-user/volumes/tomcat
             docker restart tomcat_tomcat_1
      when: build_status is succeeded
      
#    - name: deploy to kubernetes
#      shell: |
#             cd ~/gameoflife
#             kubectl apply -f kubedeploy.yml
                   
