- hosts: all
  tasks:
    - name: pull request dependent job
      debug:
        msg: "In Check label emea job"

    - name: checking the canonical name
      debug:
       msg: "{{ zuul.project.name }}"

    - shell: |
           curl -s https://api.github.com/repos/{{ zuul.project.name }}/contents/demo | jq .content
      register: encoded_file_content
    
    - set_fact:
       decoded_file_content="{{ file_content | b64decode }}"
       
    - name: stdout the decoded data
      debug:
       msg: "{{ decoded_file_content }}"
    
 #   - name: "zuul return task"
 #     zuul_return:
 #       data:
 #         zuul_location: " {{ user_location }} "
